#!/usr/bin/env python3
"""Fail if any generated theme's alarm row misses WCAG 2.1 AA contrast.

`alarms/text` and `alarms/time` are each a single shared colour applied
across all four severities (`alarms/row-low/med/high/urgent`), and
`alarms/pri-low/med/high/urgent` is a badge colour painted directly on its
own row's background -- none of these are checked by tools/check_contrast.py,
which only looks at the `--st-*`/built-in variable pairs in :root. A single
shared text or time colour can only pass if every row background sits in a
similar lightness band; nothing enforced that until this gate existed (see
the v1.17.4 leather-dark/leather-light fix).

Reads out/<theme>/globals.css (the emitted `.psc-st\\/alarms\\/...` rules,
generated by build_contract.py from contract/classes/<pack>.json -- see
contract/classes/*.json to fix a failure, then rerun build_theme.py). A row
background can be `transparent` (glass/industrial packs) or rgba() (the
alarm list shows through) -- composited over the theme's own surfaces using
check_contrast.py's read_vars()/resolve()/solid(), the same "transparent
falls back to --st-card, then flatten over --containerRoot" rule it applies
to ghost buttons, rather than reading raw rgba() channels as if opaque.

Checks, per theme, per severity (low/med/high/urgent), against that
severity's own rendered row background:
  - alarms/text  >= 4.5:1  (WCAG 1.4.3)
  - alarms/time  >= 4.5:1  (WCAG 1.4.3)
  - alarms/pri-<severity> >= 3.0:1  (WCAG 1.4.11, non-text)

Usage: tools/check_alarm_contrast.py        exit 1 on any failure
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)
sys.path.insert(0, HERE)
from build_theme import contrast_ratio, flatten, parse_colour  # noqa: E402
from check_contrast import read_vars, resolve, solid  # noqa: E402

SEVERITIES = ["low", "med", "high", "urgent"]
TEXT_FLOOR = 4.5
BADGE_FLOOR = 3.0


def _class_rules(css, name):
    """-> {prop: value} for `.psc-st\\/<name>.psc-st\\/<name> { ... }`, or {}."""
    escaped = re.escape(name).replace("/", r"\\/")
    m = re.search(r"\.psc-st\\/%s\.psc-st\\/%s\s*\{([^}]*)\}" % (escaped, escaped), css)
    if not m:
        return {}
    return dict(re.findall(r"([\w-]+)\s*:\s*([^;]+);", m.group(1)))


def _resolve_bg(raw, values, root):
    """A class's raw background-color -> a composited #rrggbb.

    `transparent` falls back to --st-card (as check_contrast.py's solid()
    does for a ghost button showing the card behind it); anything else is
    flattened over --containerRoot the same way.
    """
    if raw == "transparent":
        return solid(values, "--st-card", root)
    return flatten(raw, root) if parse_colour(raw) else None


def main():
    out = os.path.join(REPO, "out")
    failures, missing, checked = [], [], 0
    for theme in sorted(os.listdir(out)):
        theme_dir = os.path.join(out, theme)
        globals_css_path = os.path.join(theme_dir, "globals.css")
        if not os.path.isfile(globals_css_path):
            continue
        css = re.sub(r"/\*.*?\*/", "", open(globals_css_path).read(), flags=re.S)
        values = read_vars(theme_dir)
        root = resolve(values, "--containerRoot")

        text = _class_rules(css, "alarms/text").get("color")
        time_ = _class_rules(css, "alarms/time").get("color")
        list_bg_raw = _class_rules(css, "alarms/list").get("background-color")
        if not text or not time_ or not list_bg_raw or not root:
            missing.append("%s: alarms/text, alarms/time, alarms/list or --containerRoot not found" % theme)
            continue
        page = _resolve_bg(list_bg_raw, values, root)
        if not page:
            missing.append("%s: alarms/list background %r did not resolve" % (theme, list_bg_raw))
            continue

        for sev in SEVERITIES:
            row = _class_rules(css, "alarms/row-%s" % sev)
            badge = _class_rules(css, "alarms/pri-%s" % sev).get("color")
            bg_raw = row.get("background-color")
            if not bg_raw or not badge:
                missing.append("%s row-%s: background-color or pri-%s not found" % (theme, sev, sev))
                continue
            bg = _resolve_bg(bg_raw, values, page)
            if not bg:
                missing.append("%s row-%s: background %r did not resolve" % (theme, sev, bg_raw))
                continue

            checked += 3
            for label, fg_raw, floor in (("text", text, TEXT_FLOOR),
                                          ("time", time_, TEXT_FLOOR),
                                          ("badge", badge, BADGE_FLOOR)):
                if not parse_colour(fg_raw):
                    missing.append("%s row-%s %s: %r is not a plain colour" % (theme, sev, label, fg_raw))
                    continue
                fg = flatten(fg_raw, bg)
                ratio = contrast_ratio(fg, bg)
                if ratio < floor:
                    failures.append("%-14s row-%-7s %-5s %s on %s  %.2f:1 < %.1f"
                                     % (theme, sev, label, fg, bg, ratio, floor))

    for line in missing:
        print("not checked: " + line)
    for line in failures:
        print("FAIL " + line)
    print("%d checks, %d failed, %d not checked" % (checked, len(failures), len(missing)))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
